import jsPDF from "jspdf";
import html2canvas from "html2canvas";

/**
 * exportAnalysisPDF — captures the analysis result section and downloads as PDF.
 *
 * @param {string} elementId - DOM element ID to capture
 * @param {string} ticker - Stock ticker for filename
 * @param {string} signal - BUY/SELL/HOLD signal
 */
export const exportAnalysisPDF = async (elementId, ticker, signal) => {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error("exportPDF: element not found:", elementId);
    return;
  }

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#1E2433",
      logging: false,
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pageWidth - 20;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    // Header
    pdf.setFillColor(15, 17, 23);
    pdf.rect(0, 0, pageWidth, 20, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("QuantMind", 10, 13);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(148, 163, 184);
    pdf.text(`${ticker} Analysis — ${signal} Signal`, 50, 13);
    pdf.text(new Date().toLocaleDateString(), pageWidth - 10, 13, { align: "right" });

    // Content
    let yPos = 25;
    if (imgHeight <= pageHeight - 30) {
      pdf.addImage(imgData, "PNG", 10, yPos, imgWidth, imgHeight);
    } else {
      // Multi-page
      let remainingHeight = imgHeight;
      let sourceY = 0;
      while (remainingHeight > 0) {
        const sliceHeight = Math.min(remainingHeight, pageHeight - 30);
        const sliceCanvas = document.createElement("canvas");
        sliceCanvas.width = canvas.width;
        sliceCanvas.height = (sliceHeight / imgWidth) * canvas.width;
        const ctx = sliceCanvas.getContext("2d");
        ctx.drawImage(canvas, 0, sourceY, canvas.width, sliceCanvas.height, 0, 0, canvas.width, sliceCanvas.height);
        pdf.addImage(sliceCanvas.toDataURL("image/png"), "PNG", 10, yPos, imgWidth, sliceHeight);
        remainingHeight -= sliceHeight;
        sourceY += sliceCanvas.height;
        if (remainingHeight > 0) {
          pdf.addPage();
          yPos = 10;
        }
      }
    }

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(100, 116, 139);
    pdf.text("Generated by QuantMind — AI-Powered Trading Strategy Advisor", pageWidth / 2, pageHeight - 5, { align: "center" });

    pdf.save(`${ticker}_analysis_${new Date().toISOString().split("T")[0]}.pdf`);
  } catch (err) {
    console.error("exportPDF failed:", err);
    alert("PDF export failed. Try exporting as CSV instead.");
  }
};
